---
abstract: 'Fake DBI database driver simulating a database for testing error checks'
author:
  - 'Copyright 2012 Sebastian Willing, eGENTIC Systems L<http://egentic-systems.com/karriere/>'
  - 'eGENTIC Systems Sebastian Willing <sewi@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBD-Simulated
no_index:
  directory:
    - inc
    - t
recommends:
  DBI: 0
requires:
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
